# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('regdate', models.DateTimeField()),
                ('expdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('booktime', models.DurationField(default=datetime.timedelta(0))),
                ('canceltime', models.DurationField(default=datetime.timedelta(0))),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealitems', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('weekday', models.CharField(choices=[(b'MO', b'Monday'), (b'TU', b'Tuesday'), (b'WE', b'Wednesday'), (b'TH', b'Thursday'), (b'FR', b'Friday'), (b'SA', b'Saturday'), (b'SU', b'Sunday')], max_length=20)),
                ('mealid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naivedyam.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('vendor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Non_Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('default_mess', models.CharField(max_length=100)),
                ('account_balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='naivedyam.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rollno', models.CharField(max_length=20)),
                ('default_mess', models.CharField(max_length=100)),
                ('account_balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='naivedyam.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('iffile', models.BooleanField(default=False)),
                ('sgg_content', models.CharField(max_length=1000)),
                ('sgg_file', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Unregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unreg_date', models.DateField()),
                ('mealid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naivedyam.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='naivedyam.Account')),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='mealid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naivedyam.Meal'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naivedyam.Mess'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
